version: v1
name: llamafarm-1
namespace: default
prompts: []
rag:
  databases:
  - name: main_database
    type: ChromaStore
    config:
      collection_name: documents
      distance_function: cosine
      persist_directory: ./data/chroma_db
      port: 8000
    embedding_strategies:
    - name: default_embeddings
      type: OllamaEmbedder
      config:
        auto_pull: true
        base_url: http://localhost:11434/
        batch_size: 16
        dimension: 768
        model: nomic-embed-text
        timeout: 60
      priority: 0
    - name: fast_embeddings
      type: OllamaEmbedder
      config:
        auto_pull: true
        base_url: http://localhost:11434/
        batch_size: 32
        dimension: 768
        model: nomic-embed-text
        timeout: 30
      priority: 0
    retrieval_strategies:
    - name: basic_search
      type: BasicSimilarityStrategy
      config:
        distance_metric: cosine
        top_k: 10
      default: true
    - name: filtered_search
      type: MetadataFilteredStrategy
      config:
        fallback_multiplier: 2
        filter_mode: post
        top_k: 10
      default: false
    default_embedding_strategy: default_embeddings
    default_retrieval_strategy: basic_search
  data_processing_strategies:
  - name: universal_processor
    description: Single strategy handling all document types with pattern-based routing
    parsers:
    - type: PDFParser_LlamaIndex
      config:
        chunk_strategy: semantic
        chunk_size: 1000
        chunk_overlap: 200
        extract_metadata: true
        extract_images: false
        preserve_equations: true
      file_include_patterns:
      - '*.pdf'
      - '*.PDF'
      file_exclude_patterns:
      - '*_draft.pdf'
      - '*.tmp.pdf'
      - ~$*.pdf
      priority: 100
    - type: PDFParser_PyPDF2
      config:
        chunk_strategy: paragraphs
        chunk_size: 1000
        chunk_overlap: 150
        extract_metadata: true
      file_include_patterns:
      - '*.pdf'
      - '*.PDF'
      file_exclude_patterns:
      - '*_draft.pdf'
      - '*.tmp.pdf'
      - ~$*.pdf
      priority: 50
    - type: DocxParser_LlamaIndex
      config:
        chunk_size: 1000
        chunk_overlap: 150
        extract_metadata: true
      file_include_patterns:
      - '*.docx'
      - '*.DOCX'
      - '*.doc'
      - '*.DOC'
      file_exclude_patterns:
      - ~$*
      - '*.tmp'
      - '*_backup.*'
      priority: 100
    - type: CSVParser_Pandas
      config:
        chunk_size: 500
        chunk_strategy: rows
        extract_metadata: true
      file_include_patterns:
      - '*.csv'
      - '*.CSV'
      - '*.tsv'
      - '*.TSV'
      - '*.dat'
      file_exclude_patterns:
      - '*_backup.csv'
      - '*.tmp.csv'
      - ~$*.csv
      priority: 100
    - type: ExcelParser_LlamaIndex
      config:
        chunk_size: 500
        extract_metadata: true
      file_include_patterns:
      - '*.xlsx'
      - '*.XLSX'
      - '*.xls'
      - '*.XLS'
      file_exclude_patterns:
      - ~$*
      - '*.tmp.xlsx'
      - '*_backup.xlsx'
      priority: 100
    - type: MarkdownParser_Python
      config:
        chunk_size: 1000
        chunk_strategy: sections
        extract_metadata: true
        extract_code_blocks: true
        extract_links: true
      file_include_patterns:
      - '*.md'
      - '*.markdown'
      - '*.mdown'
      - '*.mkd'
      - README*
      - CHANGELOG*
      file_exclude_patterns:
      - '*.tmp.md'
      - _draft*.md
      - .*.md
      priority: 100
    - type: TextParser_Python
      config:
        chunk_size: 1000
        chunk_overlap: 100
        chunk_strategy: sentences
        extract_metadata: true
        encoding: utf-8
        clean_text: true
      file_include_patterns:
      - '*.txt'
      - '*.text'
      - '*.log'
      - '*.json'
      - '*.xml'
      - '*.yaml'
      - '*.yml'
      - '*.toml'
      - '*.cfg'
      - '*.conf'
      - '*.ini'
      - '*.properties'
      - '*.py'
      - '*.js'
      - '*.java'
      - '*.cpp'
      - '*.c'
      - '*.h'
      - '*.go'
      - '*.rs'
      - '*.sh'
      - '*.bash'
      - '*.zsh'
      - '*.ps1'
      - '*.bat'
      - LICENSE*
      - AUTHORS*
      - NOTICE*
      - COPYRIGHT*
      - '*.sql'
      - '*.css'
      - '*.html'
      - '*.htm'
      file_exclude_patterns:
      - '*.pyc'
      - '*.pyo'
      - '*.class'
      - '*.o'
      - '*.so'
      - '*.dll'
      - '*.exe'
      - '*.jpg'
      - '*.png'
      - '*.gif'
      - '*.bmp'
      - '*.ico'
      - '*.svg'
      - '*.mp3'
      - '*.mp4'
      - '*.avi'
      - '*.mov'
      - '*.wav'
      - '*.zip'
      - '*.tar'
      - '*.gz'
      - '*.rar'
      - '*.7z'
      priority: 10
    extractors:
    - type: ContentStatisticsExtractor
      config:
        include_readability: true
        include_structure: true
        include_vocabulary: true
      file_include_patterns:
      - '*'
      file_exclude_patterns: []
      priority: 100
    - type: EntityExtractor
      config:
        entity_types:
        - PERSON
        - ORG
        - GPE
        - DATE
        - PRODUCT
        - MONEY
        - PERCENT
        min_entity_length: 2
        use_fallback: true
      file_include_patterns:
      - '*'
      file_exclude_patterns: []
      priority: 90
    - type: KeywordExtractor
      config:
        algorithm: yake
        max_keywords: 10
        min_keyword_length: 3
      file_include_patterns:
      - '*'
      file_exclude_patterns: []
      priority: 80
    - type: TableExtractor
      config:
        output_format: dict
        extract_headers: true
        merge_cells: true
        min_rows: 2
      file_include_patterns:
      - '*.pdf'
      - '*.PDF'
      file_exclude_patterns: []
      priority: 100
    - type: DateTimeExtractor
      config:
        extract_relative: true
        formats:
        - ISO8601
        - US
        - EU
        extract_times: true
        extract_durations: true
      file_include_patterns:
      - '*.csv'
      - '*.tsv'
      - '*.xlsx'
      - '*.xls'
      file_exclude_patterns: []
      priority: 100
    - type: HeadingExtractor
      config:
        max_level: 6
        include_hierarchy: true
        extract_outline: true
      file_include_patterns:
      - '*.md'
      - '*.markdown'
      - '*.html'
      - '*.htm'
      - README*
      file_exclude_patterns: []
      priority: 100
    - type: LinkExtractor
      config:
        extract_urls: true
        extract_emails: true
        extract_domains: true
        validate_urls: false
      file_include_patterns:
      - '*.md'
      - '*.markdown'
      - '*.html'
      - '*.htm'
      - '*.rst'
      file_exclude_patterns: []
      priority: 90
    - type: PatternExtractor
      config:
        predefined_patterns:
        - email
        - url
        - ip_address
        - version
        custom_patterns:
        - name: import_statement
          pattern: ^import\s+.*$|^from\s+.*\s+import
          description: Import statements
        - name: function_def
          pattern: def\s+\w+\s*\(|function\s+\w+\s*\(|func\s+\w+
          description: Function definitions
        - name: class_def
          pattern: class\s+\w+[\(\:]|interface\s+\w+|struct\s+\w+
          description: Class/interface/struct definitions
      file_include_patterns:
      - '*.py'
      - '*.js'
      - '*.java'
      - '*.cpp'
      - '*.c'
      - '*.h'
      - '*.go'
      - '*.rs'
      - '*.swift'
      - '*.kt'
      - '*.scala'
      file_exclude_patterns: []
      priority: 100
datasets:
- name: rag-test-dataset
  data_processing_strategy: universal_processor
  database: main_database
  files:
  - 6d7790258c7fd47261bf8c5c1d8749225b495266b00b82f615efa06e02d6cba8
  - 41b3de4d5258cae9805eb881088cc61f8f099a93552716ab9a157e822c00bb4b
  - 33ad512e4f3acba6cf074d857be89cfbd5376e54e76fa6b1abc229c69c4ece50
  - 1d58f9207b989d7a34100b8e4f998ab1be9f5402b7cef62103a97c6d0dec1a06
runtime:
  provider: ollama
  model: llama3.1:8b
  base_url: http://localhost:11434
