# Simple PDF Processing Strategy
# Optimized for straightforward PDF document ingestion and retrieval
# This strategy provides a clean, minimal configuration for PDF-based RAG systems

strategies:
  # =============================================================================
  # SIMPLE PDF STRATEGY
  # =============================================================================
  - name: "simple_pdf"
    description: "Simple and efficient PDF document processing for RAG systems with minimal configuration"
    tags: ["pdf", "documents", "simple", "production-ready"]
    use_cases:
      - "PDF document libraries"
      - "Research paper collections"
      - "Technical documentation"
      - "Reports and white papers"
      - "E-books and manuals"
    
    components:
      parser:
        type: "PDFParser_PyPDF2"
        config:
          # Basic extraction settings
          extract_metadata: true
          extract_page_structure: true
          combine_pages: true
          page_separator: "\n\n--- Page Break ---\n\n"
          min_text_length: 10
          include_page_numbers: true
          extract_outline: true
          
          # Performance settings
          extract_images: false  # Set to true if you need image extraction
          ocr_enabled: false     # Set to true for scanned PDFs
          
          # Chunking configuration
          chunk_size: 1000       # Reasonable chunk size for most PDFs
          chunk_overlap: 100     # Small overlap to maintain context
          chunk_strategy: "characters"  # Simple character-based chunking
          respect_sentence_boundaries: true  # Don't break sentences
          respect_paragraph_boundaries: false
          min_chunk_size: 100    # Avoid tiny chunks
      
      extractors:
        # Minimal extractors for better performance
        - type: "KeywordExtractor"
          priority: 100
          config:
            algorithm: "rake"   # Fast and effective
            max_keywords: 15
            min_length: 2
            max_length: 4
            min_frequency: 1
        
        - type: "HeadingExtractor"
          priority: 90
          config:
            max_level: 3        # Extract up to h3 level
            include_hierarchy: true
            extract_outline: true
            min_heading_length: 3
      
      embedder:
        type: "OllamaEmbedder"
        config:
          model: "nomic-embed-text"
          base_url: "http://localhost:11434"
          dimension: 768
          batch_size: 16        # Balanced for performance
          timeout: 60
          auto_pull: true       # Auto-download model if missing
      
      vector_store:
        type: "ChromaStore"
        config:
          collection_name: "pdf_documents"
          persist_directory: "./data/pdf_chroma_db"
          distance_function: "cosine"
          embedding_dimension: 768
          enable_deduplication: true  # Prevent duplicate documents
      
      retrieval_strategy:
        type: "BasicSimilarityStrategy"
        config:
          top_k: 10             # Return top 10 results
          distance_metric: "cosine"
          score_threshold: 0.7  # Filter out low-quality matches

  # =============================================================================
  # ADVANCED PDF STRATEGY (with more features)
  # =============================================================================
  - name: "advanced_pdf"
    description: "Advanced PDF processing with OCR, metadata filtering, and re-ranking for complex document collections"
    tags: ["pdf", "ocr", "advanced", "high-accuracy"]
    use_cases:
      - "Scanned document archives"
      - "Mixed-format PDF collections"
      - "Legal document repositories"
      - "Academic paper databases"
      - "Multi-language documents"
    
    components:
      parser:
        type: "PDFParser_PyPDF2"
        config:
          # Enhanced extraction
          extract_metadata: true
          extract_page_structure: true
          combine_pages: false   # Keep pages separate for better granularity
          page_separator: "\n\n=== PAGE BREAK ===\n\n"
          min_text_length: 10
          include_page_numbers: true
          extract_outline: true
          extract_images: true   # Extract embedded images
          ocr_enabled: true      # Enable OCR for scanned content
          
          # Smart chunking
          chunk_size: 512        # Smaller chunks for precision
          chunk_overlap: 128     # More overlap for context
          chunk_strategy: "paragraphs"  # Paragraph-aware chunking
          respect_sentence_boundaries: true
          respect_paragraph_boundaries: true
          min_chunk_size: 50
      
      extractors:
        # Comprehensive extraction pipeline
        - type: "KeywordExtractor"
          priority: 100
          config:
            algorithm: "yake"    # More sophisticated extraction
            max_keywords: 20
            language: "en"
            max_ngram_size: 3
            deduplication_threshold: 0.9
        
        - type: "EntityExtractor"
          priority: 95
          config:
            model: "en_core_web_sm"
            entity_types: ["PERSON", "ORG", "DATE", "GPE", "MONEY", "PERCENT"]
            use_fallback: true
            merge_entities: true
            confidence_threshold: 0.7
        
        - type: "HeadingExtractor"
          priority: 90
          config:
            max_level: 6
            include_hierarchy: true
            extract_outline: true
            min_heading_length: 2
        
        - type: "DateTimeExtractor"
          priority: 85
          config:
            fuzzy_parsing: true
            extract_relative: true
            extract_times: true
            extract_durations: true
        
        - type: "SummaryExtractor"
          priority: 80
          config:
            summary_sentences: 3
            algorithm: "textrank"
            include_key_phrases: true
            include_statistics: true
        
        - type: "StatisticsExtractor"
          priority: 75
          config:
            include_readability: true
            include_vocabulary: true
            include_structure: true
            include_language: true
      
      embedder:
        type: "OllamaEmbedder"
        config:
          model: "nomic-embed-text"
          base_url: "http://localhost:11434"
          dimension: 768
          batch_size: 32        # Larger batch for efficiency
          timeout: 120          # Longer timeout for large documents
          auto_pull: true
      
      vector_store:
        type: "ChromaStore"
        config:
          collection_name: "advanced_pdf_documents"
          persist_directory: "./data/advanced_pdf_chroma_db"
          distance_function: "cosine"
          embedding_dimension: 768
          enable_deduplication: true
      
      retrieval_strategy:
        type: "RerankedStrategy"
        config:
          initial_k: 30         # Get more candidates
          final_k: 10           # Return best 10
          rerank_factors:
            similarity_weight: 0.6    # Semantic similarity
            recency_weight: 0.1       # Prefer recent documents
            length_weight: 0.1        # Prefer substantial content
            metadata_weight: 0.2      # Use metadata signals
          normalize_scores: true

  # =============================================================================
  # RESEARCH PDF STRATEGY (optimized for academic papers)
  # =============================================================================
  - name: "research_pdf"
    description: "Specialized strategy for research papers, academic articles, and technical documentation"
    tags: ["pdf", "research", "academic", "citations"]
    use_cases:
      - "Academic paper repositories"
      - "Research databases"
      - "Technical paper collections"
      - "Conference proceedings"
      - "Thesis and dissertations"
    
    components:
      parser:
        type: "PDFParser_PyPDF2"
        config:
          # Research-specific extraction
          extract_metadata: true
          extract_page_structure: true
          combine_pages: true
          page_separator: "\n\n"
          min_text_length: 20
          include_page_numbers: true
          extract_outline: true
          extract_images: false
          ocr_enabled: false
          
          # Academic paper chunking
          chunk_size: 2048       # Larger chunks for complete sections
          chunk_overlap: 256     # Substantial overlap
          chunk_strategy: "paragraphs"
          respect_sentence_boundaries: true
          respect_paragraph_boundaries: true
          min_chunk_size: 200
      
      extractors:
        # Academic-focused extractors
        - type: "KeywordExtractor"
          priority: 100
          config:
            algorithm: "yake"
            max_keywords: 30     # More keywords for research
            language: "en"
            max_ngram_size: 4    # Capture technical terms
            deduplication_threshold: 0.95
        
        - type: "EntityExtractor"
          priority: 95
          config:
            model: "en_core_web_sm"
            entity_types: ["PERSON", "ORG", "DATE", "EVENT"]  # Authors, institutions
            use_fallback: true
            merge_entities: true
        
        - type: "PatternExtractor"
          priority: 90
          config:
            predefined_patterns: ["email", "url"]  # Extract references
            custom_patterns:
              - name: "doi"
                pattern: "10\\.\\d{4,}/[-._;()/:A-Za-z0-9]+"
                description: "DOI identifiers"
              - name: "arxiv"
                pattern: "arXiv:\\d{4}\\.\\d{4,5}"
                description: "arXiv paper IDs"
            case_sensitive: false
        
        - type: "HeadingExtractor"
          priority: 85
          config:
            max_level: 6
            include_hierarchy: true
            extract_outline: true  # Important for paper structure
        
        - type: "SummaryExtractor"
          priority: 80
          config:
            summary_sentences: 5  # Longer summaries for research
            algorithm: "lsa"      # Better for technical content
            include_key_phrases: true
            include_statistics: true
      
      embedder:
        type: "OllamaEmbedder"
        config:
          model: "nomic-embed-text"
          base_url: "http://localhost:11434"
          dimension: 768
          batch_size: 8         # Smaller batch for large documents
          timeout: 180          # Longer timeout for research papers
          auto_pull: true
      
      vector_store:
        type: "ChromaStore"
        config:
          collection_name: "research_papers"
          persist_directory: "./data/research_pdf_chroma_db"
          distance_function: "cosine"
          embedding_dimension: 768
          enable_deduplication: true
      
      retrieval_strategy:
        type: "HybridUniversalStrategy"
        config:
          strategies:
            - type: "BasicSimilarityStrategy"
              weight: 0.5
              config:
                top_k: 20
                distance_metric: "cosine"
            
            - type: "MetadataFilteredStrategy"
              weight: 0.3
              config:
                top_k: 20
                filters: {}      # Can be set dynamically
                filter_mode: "pre"
            
            - type: "MultiQueryStrategy"
              weight: 0.2
              config:
                num_queries: 3
                top_k: 20
                aggregation_method: "weighted"
          
          combination_method: "weighted_average"
          final_k: 10